export const REVEAL_SIDEBAR = 'REVEAL_SIDEBAR';
export const UNREVEAL_SIDEBAR = 'UNREVEAL_SIDEBAR';

export const REVEAL_MOBILE_SIDEBAR = 'REVEAL_MOBILE_SIDEBAR';
export const UNREVEAL_MOBILE_SIDEBAR = 'UNREVEAL_MOBILE_SIDEBAR';